version: '3.8'
name: mern

services:
  nginx:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "9000:80"
    
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "3000:3000"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"

  mongodb:
    image: mongo:6.0.13-jammy
    container_name: mongoDB
    ports:
      - "27017:27017"
    volumes:
      - mongodb_config:/data/configdb
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=UvjzF_DoB5+BN9y

volumes:
  mongodb_config:
  mongodb_data:
